jvm.core.referenceMedianMillis=848
jvm.core.maxMedianMillis=1100
jvm.core.referenceP95ArticleMillis=46
jvm.core.maxP95ArticleMillis=65
jvm.core.referenceWorstArticleMillis=55
jvm.core.maxWorstArticleMillis=75
android.core.referenceMedianMillis=12930
android.core.maxMedianMillis=17000
android.core.referenceP95ArticleMillis=669
android.core.maxP95ArticleMillis=850
android.core.referenceWorstArticleMillis=944
android.core.maxWorstArticleMillis=1200
ios-simulator.core.referenceMedianMillis=3347
ios-simulator.core.maxMedianMillis=4000
ios-simulator.core.referenceP95ArticleMillis=166
ios-simulator.core.maxP95ArticleMillis=220
ios-simulator.core.referenceWorstArticleMillis=237
ios-simulator.core.maxWorstArticleMillis=310
ios-device.core.referenceMedianMillis=2798
ios-device.core.maxMedianMillis=4000
ios-device.core.referenceP95ArticleMillis=132
ios-device.core.maxP95ArticleMillis=180
ios-device.core.referenceWorstArticleMillis=197
ios-device.core.maxWorstArticleMillis=260
macos.core.referenceMedianMillis=3341
macos.core.maxMedianMillis=4000
macos.core.referenceP95ArticleMillis=168
macos.core.maxP95ArticleMillis=220
macos.core.referenceWorstArticleMillis=239
macos.core.maxWorstArticleMillis=310
