jvm.referenceMedianMillis=848
jvm.maxMedianMillis=1100
android.referenceMedianMillis=12930
android.maxMedianMillis=17000
ios-simulator.referenceMedianMillis=3347
ios-simulator.maxMedianMillis=4000
ios-device.referenceMedianMillis=2798
ios-device.maxMedianMillis=4000
macos.referenceMedianMillis=3341
macos.maxMedianMillis=4000
