name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag to publish
        required: true
        type: string
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout release tag
        if: github.event_name == 'release'
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Checkout manually selected release tag
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v7
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Cache Kotlin/Native tooling
        uses: actions/cache@v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-v1-${{ hashFiles('*.gradle.kts') }}

      - name: Publish to Maven Central
        run: ./gradlew -q --console=plain publishAndReleaseToMavenCentral --no-parallel
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
